apiVersion: v1
kind: Service
metadata:
  name: client-port-node
spec:
  type: NodePort
  ports:
  - port: 3050 # port for communication inside cluster
    targetPort: 3000 # where we will forward traffic
    nodePort: 31515 # outside world port --> will be reached from browser
  selector:
    component: web